*define,noex
:rp1
*set,v1,vx
*set,v2,vx
*if, v1, le, 0$*goto dn1$*endif
*if, v2, le, 0$*goto dn1$*endif
*get,mxsp,mxsp
spl mxsp + 1 mesh csurf v1 v2
splset, newset, splrange, mxsp + 1
vset news spls
vset add surf
vmerge,vset

*get, n, nvsp, mxsp + 1
mxve
vspfill, mxsp + 1, v1, v2, n - 2, mxve + 1, 1

*set, i, 1
:rp
*set, i, i + 1
*if, i, ge, n$*goto dn$*endif
*get, v1, nsp, i, mxsp + 1
*set, v2, mxve + i - 1
vequal, v2, v1

*goto rp
:dn
cplot
spld,mxsp + 1

*goto rp1
:dn1
*end
*loop,1,1,1
